-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
require( "ui.generated.widgets.ingame.reticles.reticleholobase" )
function DRSDigitalThermalSight( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = MenuBuilder
	local f1_local2 = f1_local0.UIElement.new()
	f1_local2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 128, 0, 128 )
	f1_local2.id = "DRSDigitalThermalSight"
	local f1_local3
	if f1_arg1 then
		f1_local3 = f1_arg1
	else
		f1_local3 = f1_arg1.controllerIndex
	end
	f1_local3 = f1_local0.ValidateControllerIndex( f1_local2, f1_local3 )
	local f1_local4 = nil
	f1_local4 = f1_local1.BuildRegisteredType( 0x4BBD8BDF7D4DFEE, {
		controllerIndex = f1_local3
	} )
	f1_local4[0x8B72E07B55C3AC0] = "ReticleHoloBase"
	f1_local4:SetRGB( 15961994, 0 )
	f1_local4:SetAnchorsAndPosition( 0,5, 0,5, 0,5, 0,5, -64, 64, -64, 64 )
	f1_local2:addElement( f1_local4 )
	f1_local2[0x4BBD8BDF7D4DFEE] = f1_local4
	return f1_local2
end

MenuBuilder.registerType( 0x5731714BEC85734, DRSDigitalThermalSight )
LockTable( _M )
