-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
function ScopeReticleParallaxer( menu, controller )
	local self = LUI.UIElement.new()
	self.id = "ScopeReticleParallaxer"
	if not controller then
		controller = {}
	end
	self:SetupScopeReticleParallaxer( controller )
	return self
end

MenuBuilder.registerType( "ScopeReticleParallaxer", ScopeReticleParallaxer )
LockTable( _M )
