-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
function PerktypeAttachment( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = MenuBuilder
	local f1_local2 = f1_local0.UIElement.new()
	f1_local2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 128, 0, 128 )
	f1_local2.id = "PerktypeAttachment"
	local f1_local3
	if f1_arg1 then
		f1_local3 = f1_arg1
	else
		f1_local3 = f1_arg1.controllerIndex
	end
	f1_local3 = f1_local0.ValidateControllerIndex( f1_local2, f1_local3 )
	local f1_local4 = nil
	f1_local4 = f1_local0.UIImage.new()
	f1_local4[0x8B72E07B55C3AC0] = "Icon"
	f1_local4:SetAlpha( 0, 0 )
	f1_local4:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 128, 0, 128 )
	f1_local2:addElement( f1_local4 )
	f1_local2[0xBFF4CC56C2092F0] = f1_local4
	return f1_local2
end

MenuBuilder.registerType( 0x31F9C837C191E58, PerktypeAttachment )
LockTable( _M )
