-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
MOBILE_HUD_BUILD_WHEN = MOBILE_HUD_BUILD_WHEN or {}
local f0_local0 = {
	SpectatingLoadout = {
		GetDataSource = function ()
			return DataSources.inGame.MP.spectating.shouldBuildMobileSpectatorLayer
		end
	},
	MobileOpenSpectatingLoadoutButton = {
		GetDataSource = function ()
			return DataSources.inGame.MP.spectating.shouldBuildMobileSpectatorLayer
		end
	},
	SpectatorRequestRedeploy = {
		GetDataSource = function ()
			return DataSources.inGame.MP.spectating.shouldBuildMobileSpectatorLayer
		end
	},
	SpectatorEquipmentSection = {
		GetDataSource = function ()
			return DataSources.inGame.MP.spectating.shouldBuildMobileSpectatorLayer
		end
	},
	SpectatorArmorHealth = {
		GetDataSource = function ()
			return DataSources.inGame.MP.spectating.shouldBuildMobileSpectatorLayer
		end
	},
	SpectatorPlayerCard = {
		GetDataSource = function ()
			return DataSources.inGame.MP.spectating.shouldBuildMobileSpectatorLayer
		end
	}
}
MOBILE_HUD_BUILD_WHEN.GetBuildWhenDataSource = function ( f1_arg0 )
	if not f1_arg0 or not f0_local0[f1_arg0] then
		return 
	else
		return f0_local0[f1_arg0].GetDataSource()
	end
end

