-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
LUI.UIImage = LUI.Class( LUI.UIElement )
LUI.UIImage.build = function ( f4_arg0, f4_arg1 )
	return LUI.UIImage.new()
end

LUI.UIImage.init = function ( f3_arg0 )
	LUI.UIElement.init( f3_arg0 )
	f3_arg0:setupUIImage()
	f3_arg0._typeName = "uiimage"
end

LUI.UIImage.id = "LUIImage"
LUI.UITriangleImage = LUI.Class( LUI.UIElement )
LUI.UITriangleImage.build = function ( f2_arg0, f2_arg1 )
	return LUI.UITriangleImage.new()
end

LUI.UITriangleImage.init = function ( f1_arg0 )
	LUI.UIElement.init( f1_arg0 )
	f1_arg0:setupUITriangleImage()
end

LUI.UITriangleImage.id = "UITriangleImage"
