-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
DevActions = DevActions or {}
DevActions = {
	OpeningIW9MainMenu = function ()
		if CONDITIONS.IsDevelopmentBuild() then
			LUI.FlowManager.RequestRestoreMenu( "MainMenu", nil, nil )
		end
	end,
	OpeningIW9OfflineMenu = function ()
		if CONDITIONS.IsDevelopmentBuild() then
			LUI.FlowManager.RequestRestoreMenu( "MainMenuOffline", nil, nil )
		end
	end,
	OpeningIW9LockoutMenu = function ()
		if CONDITIONS.IsDevelopmentBuild() then
			LUI.FlowManager.RequestRestoreMenu( "MainLockoutMenu", nil, nil )
		end
	end,
	TestAction = function ( f1_arg0, f1_arg1 )
		
	end
}
