-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
WeGame = WeGame or {}
WeGame.WhitelistGameMaps = function ( f2_arg0 )
	local f2_local0 = {
		nil,
		"cp_br_syrk"
	}
	local f2_local1 = {}
	for f2_local8, f2_local9 in ipairs( f2_arg0 ) do
		for f2_local5, f2_local6 in ipairs( f2_local0 ) do
			if f2_local9.ref == f2_local6 then
				table.insert( f2_local1, f2_local9 )
			end
		end
	end
	return f2_local1
end

WeGame.PopupHealthyTipsIfNeeded = function ()
	if Dvar[0x9E5BE3B4BBA4E0E]( 0x1E1D0BA4927E743 ) then
		return false
	else
		Dvar[0x8EA06EEDB58D872]( 0x1E1D0BA4927E743, true )
		LUI.FlowManager.RequestPopupMenu( nil, "WeGameHealthyTips" )
		return true
	end
end

