-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
function MPDepotMenuHorizontalButtons( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = f1_local0.UIHorizontalList.new()
	f1_local1:SetAlignment( f1_local0.Alignment.Left )
	f1_local1:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 1578, 0, 270 )
	f1_local1.id = "MPDepotMenuHorizontalButtons"
	local f1_local2
	if f1_arg1 then
		f1_local2 = f1_arg1
	else
		f1_local2 = f1_arg1.controllerIndex
	end
	f1_local2 = f1_local0.ValidateControllerIndex( f1_local1, f1_local2 )
	f1_local1:SetSpacing( 20 )
	return f1_local1
end

MenuBuilder.registerType( 0xC221C8AB458943A, MPDepotMenuHorizontalButtons )
LockTable( _M )
