-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
LUI.UIRepeatedImage = LUI.Class( LUI.UIElement )
LUI.UIRepeatedImage.build = function ( f2_arg0, f2_arg1 )
	return LUI.UIRepeatedImage.new()
end

LUI.UIRepeatedImage.init = function ( f1_arg0 )
	LUI.UIElement.init( f1_arg0 )
	f1_arg0:SetupRepeatedImage()
end

LUI.UIRepeatedImage.id = "LUIRepeatedImage"
