-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
return function ()
	return Lazy.Table.new( {
		[0x8B6F2336E5960E5] = require( "ui.generated.datasources.frontend-operators-west-operator-unlock-criteria_list_element-bundle", false ),
		[0x73F002E1BA79F9E] = require( "ui.generated.datasources.frontend-operators-west-operator-unlock-criteria_list_element-challenge", false ),
		[0x5BB26B73B85755] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.west.operator.unlock.criteria_list_element.is_available", false )
		end
		,
		[0x3DDD866B4F2C25] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.west.operator.unlock.criteria_list_element.is_complete", false )
		end
		,
		[0xBD068E64DD33F7B] = require( "ui.generated.datasources.frontend-operators-west-operator-unlock-criteria_list_element-prompt", false ),
		[0xA04F4EF1995407E] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.west.operator.unlock.criteria_list_element.text", "" )
		end
		,
		[0x79439EF7BFA9C2D] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.west.operator.unlock.criteria_list_element.type", "" )
		end
		,
		[0xC1CCDF88C25B583] = require( "ui.generated.datasources.frontend-operators-west-operator-unlock-criteria_list_element-win_challenge", false ),
		GetModel = function ()
			return function ( f3_arg0, f3_arg1 )
				local f3_local0 = LUI.DataSourceInGlobalModel.new( "frontend.operators.west.operator.unlock.criteria_list_element" )
				return f3_local0:GetModel( f3_arg1 )
			end
			
		end
		
	} )
end

