-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
local f0_local0 = function ( f2_arg0, f2_arg1, f2_arg2 )
	f2_arg0:ReceivePostFXLite()
end

function ReticleSniper02( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = MenuBuilder
	local f1_local2 = f1_local0.UIElement.new()
	f1_local2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 20, 0, 20 )
	f1_local2.id = "ReticleSniper02"
	local f1_local3
	if f1_arg1 then
		f1_local3 = f1_arg1
	else
		f1_local3 = f1_arg1.controllerIndex
	end
	f1_local3 = f1_local0.ValidateControllerIndex( f1_local2, f1_local3 )
	local f1_local4 = nil
	f1_local4 = f1_local0.UIImage.new()
	f1_local4[0x8B72E07B55C3AC0] = "Center"
	f1_local4:SetRGB( 0, 0 )
	f1_local4:setImage( RegisterMaterial( 0x32926AE567B3207 ), 0 )
	f1_local4:SetUMin( 0,01, 0 )
	f1_local4:SetVMax( 0,99, 0 )
	f1_local4:SetAnchorsAndPosition( 0, 1, 0, 1, -62, 82, -62, 82 )
	f1_local2:addElement( f1_local4 )
	f1_local2[0xF4B7EC4DCAA8AC4] = f1_local4
	local f1_local5 = nil
	f1_local5 = f1_local0.UIImage.new()
	f1_local5[0x8B72E07B55C3AC0] = "Top"
	f1_local5:SetRGB( 0, 0 )
	f1_local5:setImage( RegisterMaterial( 0x32926AE567B3207 ), 0 )
	f1_local5:SetUMin( 0,49, 0 )
	f1_local5:SetUMax( 0,52, 0 )
	f1_local5:SetVMax( 0,15, 0 )
	f1_local5:SetAnchorsAndPosition( 0, 1, 0, 1, 4, 17, -700, -28 )
	f1_local2:addElement( f1_local5 )
	f1_local2[0x6F9BC194465A83C] = f1_local5
	local f1_local6 = nil
	f1_local6 = f1_local0.UIImage.new()
	f1_local6[0x8B72E07B55C3AC0] = "Bottom"
	f1_local6:SetRGB( 0, 0 )
	f1_local6:setImage( RegisterMaterial( 0x32926AE567B3207 ), 0 )
	f1_local6:SetUMin( 0,49, 0 )
	f1_local6:SetUMax( 0,52, 0 )
	f1_local6:SetVMax( 0,15, 0 )
	f1_local6:SetAnchorsAndPosition( 0, 1, 0, 1, 4, 17, 48, 700 )
	f1_local2:addElement( f1_local6 )
	f1_local2[0x117B24625D0110A] = f1_local6
	local f1_local7 = nil
	f1_local7 = f1_local0.UIImage.new()
	f1_local7[0x8B72E07B55C3AC0] = "Left"
	f1_local7:SetRGB( 0, 0 )
	f1_local7:SetZRotation( 90, 0 )
	f1_local7:setImage( RegisterMaterial( 0x32926AE567B3207 ), 0 )
	f1_local7:SetUMin( 0,49, 0 )
	f1_local7:SetUMax( 0,52, 0 )
	f1_local7:SetVMax( 0,15, 0 )
	f1_local7:SetAnchorsAndPosition( 0, 1, 0, 1, -346, -334, -302, 322 )
	f1_local2:addElement( f1_local7 )
	f1_local2[0x4B070ADA2041CB0] = f1_local7
	local f1_local8 = nil
	f1_local8 = f1_local0.UIImage.new()
	f1_local8[0x8B72E07B55C3AC0] = "Right"
	f1_local8:SetRGB( 0, 0 )
	f1_local8:SetZRotation( 90, 0 )
	f1_local8:setImage( RegisterMaterial( 0x32926AE567B3207 ), 0 )
	f1_local8:SetUMin( 0,49, 0 )
	f1_local8:SetUMax( 0,52, 0 )
	f1_local8:SetVMax( 0,15, 0 )
	f1_local8:SetAnchorsAndPosition( 0, 1, 0, 1, 363, 375, -312, 332 )
	f1_local2:addElement( f1_local8 )
	f1_local2[0x6AAAA535714D805] = f1_local8
	f0_local0( f1_local2, f1_local3, f1_arg1 )
	return f1_local2
end

MenuBuilder.registerType( 0x8C3D9F49629EE72, ReticleSniper02 )
LockTable( _M )
