-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
require( "ui.generated.widgets.buttonhelperbar" )
require( "ui.generated.widgets.buttonpromptcontainerhorizontal" )
local f0_local0 = function ( f7_arg0 )
	if f7_arg0.ButtonHelperBar.ButtonHelperText:GetPromptByButtonRef( f7_arg0._keyboardBinding ) then
		f7_arg0.ButtonHelperBar.ButtonHelperText:RemoveButtonPrompt( f7_arg0._keyboardBinding )
	end
	if f7_arg0.ButtonHelperBar.ButtonHelperText:GetPromptByButtonRef( f7_arg0._gamepadBinding ) then
		f7_arg0.ButtonHelperBar.ButtonHelperText:RemoveButtonPrompt( f7_arg0._gamepadBinding )
	end
	local f7_local0 = LUI.IsGamepadActiveInputMethodForPrompts( f7_arg0._controllerIndex )
	if not f7_local0 or not f7_arg0._gamepadBinding then
		local f7_local1 = f7_arg0._keyboardBinding
	end
	local f7_local2 = function ( f9_arg0 )
		if f7_arg0._longPress or f9_arg0.event.name ~= "gamepad_button" then
			f7_arg0._callback( f9_arg0.element, f9_arg0.event )
		end
	end
	
	local f7_local3 = true
	if not f7_local0 and not f7_arg0._keyboardBinding then
		local f7_local1 = f7_arg0._gamepadBinding
		f7_local3 = false
	end
	local f7_local4, f7_local5 = nil
	local f7_local6 = LAYOUT.GetHorizontalAlignment( f7_arg0 )
	if f7_local6 == LUI.Alignment.Right then
		f7_local4 = LUI.Alignment.Right
	elseif f7_local6 == LUI.Alignment.Center then
		f7_local5 = LUI.Alignment.Center
	else
		
	end
	f7_arg0.ButtonHelperBar.ButtonHelperText:PushButtonPrompt( {
		ignoreTooltipPrompt = true,
		forceShowPrimaryBtn = true,
		helper_text = f7_arg0._buttonText,
		button_ref = f7_local1,
		setButtonContainerAlignment = f7_local4,
		setContainerAlignment = f7_local5,
		clickable = not f7_local0,
		container = f7_arg0.ButtonContainer,
		kbmTooltipPromptOverload = f7_local1,
		isIconEnabledForKBM = f7_local3,
		callback = f7_local2,
		isHold = f7_arg0._longPress,
		holdDuration = f7_arg0._longPressDuration
	} )
	f7_arg0:registerEventHandler( "gamepad_button", function ( element, event )
		if not element._longPress and element:IsVisible() and event.down and "button_" .. event.button == element._gamepadBinding then
			element:_callback( event )
		end
	end )
end

local f0_local1 = function ( f5_arg0, f5_arg1, f5_arg2 )
	f5_arg0._controllerIndex = f5_arg1
	f5_arg0._buttonText = f5_arg2.buttonText
	f5_arg0._keyboardBinding = f5_arg2.keyboardBinding
	f5_arg0._gamepadBinding = f5_arg2.gamepadBinding
	f5_arg0._callback = f5_arg2.callback
	f5_arg0._longPress = f5_arg2.longPress
	f5_arg0._longPressDuration = f5_arg2.longPressDuration
	f0_local0( f5_arg0 )
	f5_arg0:SubscribeToInputTypeModel( f5_arg1, function ( f6_arg0, f6_arg1 )
		f5_arg0( f6_arg1 )
	end )
end

local f0_local2 = function ( f4_arg0, f4_arg1 )
	f4_arg0._buttonText = f4_arg1
	f0_local0( f4_arg0 )
end

local f0_local3 = function ( f3_arg0, f3_arg1, f3_arg2 )
	f3_arg0._longPress = f3_arg1
	f3_arg0._longPressDuration = f3_arg2
	f0_local0( f3_arg0 )
end

local f0_local4 = function ( f2_arg0, f2_arg1, f2_arg2 )
	f2_arg0.Setup = f0_local0
	f2_arg0.SetText = f0_local0
	f2_arg0.SetLongPress = f0_local0
end

function MiniStoreInputPrompt( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = MenuBuilder
	local f1_local2 = f1_local0.UIElement.new()
	f1_local2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 200, 0, 80 )
	f1_local2.id = "MiniStoreInputPrompt"
	local f1_local3
	if f1_arg1 then
		f1_local3 = f1_arg1
	else
		f1_local3 = f1_arg1.controllerIndex
	end
	f1_local3 = f1_local0.ValidateControllerIndex( f1_local2, f1_local3 )
	local f1_local4 = nil
	f1_local4 = f1_local1.BuildRegisteredType( 0x8608EBDC1924A2E, {
		controllerIndex = f1_local3
	} )
	f1_local4[0x8B72E07B55C3AC0] = "ButtonHelperBar"
	f1_local4:SetAnchorsAndPosition( 0, 0, 0, 0, 0, 0, 0, 0 )
	f1_local2:addElement( f1_local4 )
	f1_local2[0x8608EBDC1924A2E] = f1_local4
	local f1_local5 = nil
	f1_local5 = f1_local1.BuildRegisteredType( 0x5339A49D65C4D76, {
		controllerIndex = f1_local3
	} )
	f1_local5[0x8B72E07B55C3AC0] = "ButtonContainer"
	f1_local5:SetAnchorsAndPosition( 0, 0, 0, 0, 0, 0, 0, 0 )
	f1_local2:addElement( f1_local5 )
	f1_local2[0x873DD5BC0F7F234] = f1_local5
	f0_local0( f1_local2, f1_local3, f1_arg1 )
	return f1_local2
end

MenuBuilder.registerType( 0x34579810ED28677, MiniStoreInputPrompt )
LockTable( _M )
