-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
return function ()
	return Lazy.Table.new( {
		[0x55B556730A34A05] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.west.operator.unlock.criteria_list_element.bundle.data", false )
		end
		,
		[0xCC44970C8397929] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.west.operator.unlock.criteria_list_element.bundle.description", "" )
		end
		,
		[0xAB612888528489A] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.west.operator.unlock.criteria_list_element.bundle.image", "ui_shared_transparent" )
		end
		,
		[0xBD068E64DD33F7B] = require( "ui.generated.datasources.frontend-operators-west-operator-unlock-criteria_list_element-bundle-prompt", false ),
		[0xA31296C0C1B6029] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.west.operator.unlock.criteria_list_element.bundle.title", "" )
		end
		,
		GetModel = function ()
			return function ( f3_arg0, f3_arg1 )
				local f3_local0 = LUI.DataSourceInGlobalModel.new( "frontend.operators.west.operator.unlock.criteria_list_element.bundle" )
				return f3_local0:GetModel( f3_arg1 )
			end
			
		end
		
	} )
end

