-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
return function ()
	return Lazy.Table.new( {
		GetModel = function ()
			return function ( f3_arg0, f3_arg1 )
				local f3_local0 = LUI.DataSourceInGlobalModel.new( "customization" )
				return f3_local0:GetModel( f3_arg1 )
			end
			
		end
		
	} )
end

