-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
FTUE.WidgetManager = LUI.Class()
FTUE.WidgetManager.init = function ( f4_arg0 )
	f4_arg0._mapIdWidget = {}
end

FTUE.WidgetManager.Register = function ( f3_arg0, f3_arg1, f3_arg2 )
	f3_arg0._mapIdWidget[f3_arg1] = f3_arg2
end

FTUE.WidgetManager.Unregister = function ( f2_arg0, f2_arg1 )
	f2_arg0._mapIdWidget[f2_arg1] = nil
end

FTUE.WidgetManager.GetWidgetById = function ( f1_arg0, f1_arg1 )
	return f1_arg0._mapIdWidget[f1_arg1]
end

