-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
LUI.Cinematic = LUI.Class( LUI.UIElement )
LUI.Cinematic.init = function ( f2_arg0, f2_arg1 )
	if not f2_arg1 then
		f2_arg1 = {}
	end
	LUI.Cinematic.super.init( f2_arg0, f2_arg1 )
	f2_arg0:SetupCinematic( f2_arg1 )
end

LUI.Cinematic.id = "LUICinematic"
MenuBuilder.registerType( "Cinematic", function ( f1_arg0, f1_arg1 )
	return LUI.Cinematic.new( f1_arg1 )
end )
