-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
require( "ui.generated.widgets.ingame.reticles.reddot" )
local f0_local0 = function ( f2_arg0, f2_arg1, f2_arg2 )
	f2_arg0:ReceivePostFXLite()
end

function ReticleACOGEast( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = MenuBuilder
	local f1_local2 = f1_local0.UIElement.new()
	f1_local2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 0, 0, 0 )
	f1_local2.id = "ReticleACOGEast"
	local f1_local3
	if f1_arg1 then
		f1_local3 = f1_arg1
	else
		f1_local3 = f1_arg1.controllerIndex
	end
	f1_local3 = f1_local0.ValidateControllerIndex( f1_local2, f1_local3 )
	local f1_local4 = nil
	f1_local4 = f1_local1.BuildRegisteredType( 0x187270BF5A054E3, {
		controllerIndex = f1_local3
	} )
	f1_local4[0x8B72E07B55C3AC0] = "RedDot"
	f1_local4:SetAnchorsAndPosition( 1, 1, 1, 1, -5, 5, -5, 5 )
	f1_local2:addElement( f1_local4 )
	f1_local2[0x187270BF5A054E3] = f1_local4
	f0_local0( f1_local2, f1_local3, f1_arg1 )
	return f1_local2
end

MenuBuilder.registerType( 0x36599812750A810, ReticleACOGEast )
LockTable( _M )
