-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
return function ()
	return Lazy.Table.new( {
		[0xCC44970C8397929] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.east.operator.unlock.criteria_list_element.win_challenge.challenge.description", "" )
		end
		,
		[0x9909144862249C6] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.east.operator.unlock.criteria_list_element.win_challenge.challenge.progress", 0 )
		end
		,
		[0x29EE3E9D98BC053] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.east.operator.unlock.criteria_list_element.win_challenge.challenge.progress_max", 0 )
		end
		,
		[0xAC8300EBFFAC996] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.east.operator.unlock.criteria_list_element.win_challenge.challenge.progress_normalized", 0 )
		end
		,
		[0xAA417222E7B0C6C] = function ()
			return LUI.DataSourceInControllerModel.new( "frontend.operators.east.operator.unlock.criteria_list_element.win_challenge.challenge.progress_text", "" )
		end
		,
		GetModel = function ()
			return function ( f3_arg0, f3_arg1 )
				local f3_local0 = LUI.DataSourceInGlobalModel.new( "frontend.operators.east.operator.unlock.criteria_list_element.win_challenge.challenge" )
				return f3_local0:GetModel( f3_arg1 )
			end
			
		end
		
	} )
end

