-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
local f0_local0 = function ( f2_arg0, f2_arg1, f2_arg2 )
	AddMobileButtonLogic( f2_arg0 )
	f2_arg0:addEventHandler( "button_action", function ( f4_arg0, f4_arg1 )
		if f4_arg0._buttonActionOverwrite then
			f4_arg0:_buttonActionOverwrite()
		else
			ACTIONS.LeaveMenu( f4_arg0:GetCurrentMenu() )
		end
	end )
	f2_arg0.SetButtonAction = function ( f3_arg0, f3_arg1 )
		f3_arg0._buttonActionOverwrite = f3_arg1
	end
	
end

function MobileSettingsBackButton( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = MenuBuilder
	local f1_local2 = f1_local0.UIButton.new()
	f1_local2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 111, 0, 84 )
	f1_local2.id = "MobileSettingsBackButton"
	local f1_local3
	if f1_arg1 then
		f1_local3 = f1_arg1
	else
		f1_local3 = f1_arg1.controllerIndex
	end
	f1_local3 = f1_local0.ValidateControllerIndex( f1_local2, f1_local3 )
	local f1_local4 = nil
	f1_local4 = f1_local0.UIImage.new()
	f1_local4[0x8B72E07B55C3AC0] = "BackIcon"
	f1_local4:SetRGB( 15198183, 0 )
	f1_local4:SetAlpha( 0,3, 0 )
	f1_local4:setImage( RegisterMaterial( 0x5CFD274254277A7 ), 0 )
	f1_local4:SetAnchorsAndPosition( 0,5, 0,5, 0,5, 0,5, -37,5, 37,5, -44,5, 44,5 )
	f1_local2:addElement( f1_local4 )
	f1_local2[0x2174D07DC898CAF] = f1_local4
	f0_local0( f1_local2, f1_local3, f1_arg1 )
	return f1_local2
end

MenuBuilder.registerType( 0x2CBF0D20C210CCD, MobileSettingsBackButton )
LockTable( _M )
