-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
LUI.UIPrettyNumber = LUI.Class( LUI.UIText )
LUI.UIPrettyNumber.init = function ( f1_arg0, f1_arg1 )
	f1_arg1.precision = f1_arg1.precision or 1
	LUI.UIText.init( f1_arg0 )
	f1_arg0.id = "UIPrettyNumber"
	if f1_arg0.setupPrettyNumber then
		f1_arg0:setupPrettyNumber( f1_arg1.speed, f1_arg1.initialValue, f1_arg1.precision )
	end
end

