-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
FenceUGCPrivilege = LUI.Class( LUI.Fence )
FenceUGCPrivilege.init = function ( f5_arg0 )
	LUI.Fence.init( f5_arg0 )
end

FenceUGCPrivilege.Start = function ( f4_arg0 )
	
end

FenceUGCPrivilege.Stop = function ( f3_arg0 )
	
end

FenceUGCPrivilege.OpenSignInQueuedPopup = function ( f2_arg0 )
	local f2_local0 = f2_arg0
	LUI.FlowManager.RequestPopupMenu( nil, "popup_signin_queue", false, nil, false, {}, nil, true, true )
	f2_arg0._openedWaitPopup = "popup_signin_queue"
end

FenceUGCPrivilege.UpdateState = function ( f1_arg0 )
	f1_arg0._state = LUI.Fence.STATE.pass
	if not Engine[0x9D348E40740E9A8]() then
		return 
	else
		f1_arg0._state = FencePrivilegeUtils.ProcessPrivilegeState( f1_arg0, Enum[0x7D294D36FF8AE1B][0x2ED131D38CD871C], false )
	end
end

LUI.Fence.Register( "ugcPrivilege", FenceUGCPrivilege )
LockTable( _M )
