-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
local f0_local0 = function ( f3_arg0, f3_arg1 )
	if not String.IsNilOrEmpty( f3_arg1 ) then
		f3_arg0.Logo:setImage( RegisterMaterial( f3_arg1 ) )
	end
end

local f0_local1 = function ( f2_arg0, f2_arg1, f2_arg2 )
	f2_arg0.SetIcon = f0_local0
end

function GameLogo( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = MenuBuilder
	local f1_local2 = f1_local0.UIElement.new()
	f1_local2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 90, 0, 30 )
	f1_local2.id = "GameLogo"
	local f1_local3
	if f1_arg1 then
		f1_local3 = f1_arg1
	else
		f1_local3 = f1_arg1.controllerIndex
	end
	f1_local3 = f1_local0.ValidateControllerIndex( f1_local2, f1_local3 )
	local f1_local4 = nil
	f1_local4 = f1_local0.UIImage.new()
	f1_local4[0x8B72E07B55C3AC0] = "Logo"
	f1_local4:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 90, 0, 30 )
	f1_local2:addElement( f1_local4 )
	f1_local2[0xE07F1AD70EC5BBA] = f1_local4
	f0_local0( f1_local2, f1_local3, f1_arg1 )
	return f1_local2
end

MenuBuilder.registerType( 0xC0151B2C97BE778, GameLogo )
LockTable( _M )
