-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
require( "ui.generated.widgets.frontend.unlockcriteria.criteriawidgets.unlockcriteriabase" )
function UnlockCriteriaPlayerProgression( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = MenuBuilder.BuildRegisteredType( 0x1B94156EAB96C39, f1_arg1 )
	f1_local1:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 600, 0, 36 )
	f1_local1.id = "UnlockCriteriaPlayerProgression"
	local f1_local2
	if f1_arg1 then
		f1_local2 = f1_arg1
	else
		f1_local2 = f1_arg1.controllerIndex
	end
	f1_local2 = f1_local0.ValidateControllerIndex( f1_local1, f1_local2 )
	f1_local0.UIElement.ValidateAnimationState( f1_local1 )
	return f1_local1
end

MenuBuilder.registerType( 0x9200E3DED561DA4, UnlockCriteriaPlayerProgression )
LockTable( _M )
