-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
local f0_local0 = function ( f3_arg0 )
	return 38 + LAYOUT.GetTextWidth( f3_arg0.FreeText, f3_arg0._controllerIndex )
end

local f0_local1 = function ( f2_arg0, f2_arg1, f2_arg2 )
	f2_arg0._controllerIndex = f2_arg1
	f2_arg0.GetFreeTagWidth = f0_local0
end

function StoreFreeTag( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = MenuBuilder
	local f1_local2 = f1_local0.UIElement.new()
	f1_local2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 100, 0, 34 )
	f1_local2.id = "StoreFreeTag"
	local f1_local3
	if f1_arg1 then
		f1_local3 = f1_arg1
	else
		f1_local3 = f1_arg1.controllerIndex
	end
	f1_local3 = f1_local0.ValidateControllerIndex( f1_local2, f1_local3 )
	local f1_local4 = nil
	f1_local4 = f1_local0.UIImage.new()
	f1_local4[0x8B72E07B55C3AC0] = "Image"
	f1_local4:SetRGB( SWATCHES[0xEAF2060ABE5269B][0x95F8FA57EF1A27B], 0 )
	f1_local4:setImage( RegisterMaterial( 0xE31B7C5CAD73D13 ), 0 )
	f1_local4:SetAnchorsAndPosition( 0, 1, 0,5, 0,5, 0, 32, -16, 16 )
	f1_local2:addElement( f1_local4 )
	f1_local2[0xAB612888528489A] = f1_local4
	local f1_local5 = nil
	f1_local5 = f1_local0.UIStyledText.new()
	f1_local5[0x8B72E07B55C3AC0] = "FreeText"
	f1_local5:SetRGB( SWATCHES[0xEAF2060ABE5269B][0x95F8FA57EF1A27B], 0 )
	f1_local5:setText( Engine[0xED84C33EC5F01EA]( 0x3B6483D600AF632 ), 0 )
	f1_local5:SetFont( FONTS.GetFont( FONTS.SecondaryRegular.File ) )
	f1_local5:SetFontSize( 20 * _PT )
	f1_local5:SetMinFontSize( 20 * _PT )
	f1_local5:SetWordWrap( false )
	f1_local5:SetAlignment( f1_local0.Alignment.Left )
	f1_local5:SetAnchorsAndPosition( 0, 1, 0,5, 0,5, 38, 100, -12, 8 )
	f1_local2:addElement( f1_local5 )
	f1_local2[0x5E8E464D89C68C] = f1_local5
	f0_local0( f1_local2, f1_local3, f1_arg1 )
	return f1_local2
end

MenuBuilder.registerType( 0x1998A1F3A5779C4, StoreFreeTag )
LockTable( _M )
