-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
LabelUtils = LabelUtils or {}
LabelUtils.AlignmentTypes = {
	RIGHT = 2,
	MULTI = 4,
	LEFT = 1,
	NO_BACKING = 3
}
LabelUtils.TimerTypes = {
	COMING_SOON = 2,
	EXPIRING = 1
}
LabelUtils.Alignment = {
	[LabelUtils.AlignmentTypes.LEFT] = "Left",
	[LabelUtils.AlignmentTypes.RIGHT] = "Right",
	[LabelUtils.AlignmentTypes.NO_BACKING] = "NoBacking",
	[LabelUtils.AlignmentTypes.MULTI] = "Multi"
}
LabelUtils.Timer = {
	[LabelUtils.TimerTypes.EXPIRING] = "Expiring",
	[LabelUtils.TimerTypes.COMING_SOON] = "ComingSoon"
}
