-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
XHash = XHash or {}
XHash.IsNilOrInvalidXHashAsset = XHashInt[0x3C667D78516253C]
XHash.ConvertTableKeysToXhash = XHashInt[0x976050AED2BE7DB]
XHash.SetAutoXHashMetatable = XHashInt[0x8E3DCA4146A6C2F]
XHash.AssertOnTypeNameString = XHashInt[0xFA08F50830658D8]
XHash.AssertOnEventHandlerStringKey = XHashInt[0x2CB0B26C46C75BA]
XHash.AssertOnSequenceStringKey = XHashInt[0xA7B3E3DE7B19B49]
