-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
function ModuleInaccessible( f2_arg0 )
	_G[f2_arg0] = setmetatable( {}, {
		__index = function ( f3_arg0, f3_arg1 )
			return function ()
				
			end
			
		end
	} )
end

if Engine then
	Engine[0xAD041992EB2AEC9] = Engine[0xAD041992EB2AEC9] or function ()
		return false
	end
	
end
if Game then
	
else
	ModuleInaccessible( "Game" )
end
if Friends then
	
else
	ModuleInaccessible( "Friends" )
end
if Leaderboards then
	
else
	ModuleInaccessible( "Leaderboards" )
end
if Lobby then
	
else
	ModuleInaccessible( "Lobby" )
end
if LobbyMember then
	
else
	ModuleInaccessible( "LobbyMember" )
end
if Playlist then
	
else
	ModuleInaccessible( "Playlist" )
end
MLG = MLG or {}
Customization = Customization or {}
MatchRules = MatchRules or {}
