-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
local f0_local0 = function ( f2_arg0, f2_arg1, f2_arg2 )
	local f2_local0 = nil
	f2_local0 = MenuBuilder.BuildRegisteredType( 0x889D3025C1FC5E8, f2_arg2 )
	f2_local0[0x8B72E07B55C3AC0] = "BattlePassUpsellPopup"
	f2_local0:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 1920, 0, 1080 )
	f2_arg0:addElement( f2_local0 )
	f2_arg0[0x8A70D5DEF355B03] = f2_local0
end

function JupBattlePassUpsellPopupMenu( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = f1_local0.UIMenu.new()
	f1_local1.id = "JupBattlePassUpsellPopupMenu"
	local f1_local2
	if f1_arg1 then
		f1_local2 = f1_arg1
	else
		f1_local2 = f1_arg1.controllerIndex
	end
	f1_local2 = f1_local0.ValidateControllerIndex( f1_local1, f1_local2 )
	local f1_local3 = f1_local1
	f0_local0( f1_local1, f1_local2, f1_arg1 )
	return f1_local1
end

MenuBuilder.registerType( 0x56B21122641F90F, JupBattlePassUpsellPopupMenu )
LockTable( _M )
