-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
return function ()
	return Lazy.Table.new( {
		[0x8C0303DBBBA6C3C] = function ()
			return LUI.DataSourceInGlobalModel.new( "cg.winnersCircle.notify", false )
		end
		,
		[0x5DC458B7C579C68] = function ()
			return LUI.DataSourceInGlobalModel.new( "cg.winnersCircle.showTaunt", false )
		end
		,
		GetModel = function ()
			return function ( f3_arg0, f3_arg1 )
				local f3_local0 = LUI.DataSourceInGlobalModel.new( "cg.winnersCircle" )
				return f3_local0:GetModel( f3_arg1 )
			end
			
		end
		
	} )
end

