-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 11-02-2024 16:22
module( ..., package.seeall )
require( "ui.generated.widgets.frontend.social.socialplayeremblem" )
local f0_local0 = function ( f2_arg0, f2_arg1, f2_arg2 )
	if f2_arg0.SocialPlayerEmblem then
		f2_arg0.SocialPlayerEmblem:SetEmpty()
	end
end

function SocialProfileCardSmallEmpty( f1_arg0, f1_arg1 )
	local f1_local0 = LUI
	local f1_local1 = MenuBuilder
	local f1_local2 = f1_local0.UIElement.new()
	f1_local2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 528, 0, 124 )
	f1_local2.id = "SocialProfileCardSmallEmpty"
	local f1_local3
	if f1_arg1 then
		f1_local3 = f1_arg1
	else
		f1_local3 = f1_arg1.controllerIndex
	end
	f1_local3 = f1_local0.ValidateControllerIndex( f1_local2, f1_local3 )
	local f1_local4 = nil
	f1_local4 = f1_local0.UIImage.new()
	f1_local4[0x8B72E07B55C3AC0] = "Background"
	f1_local4:setImage( RegisterMaterial( 0xB68EAC679025FFC ), 0 )
	f1_local2:addElement( f1_local4 )
	f1_local2[0xD4176E7CA246EDD] = f1_local4
	local f1_local5 = nil
	f1_local5 = f1_local1.BuildRegisteredType( 0xB2805BEA6897965, {
		controllerIndex = f1_local3
	} )
	f1_local5[0x8B72E07B55C3AC0] = "SocialPlayerEmblem"
	f1_local5:SetAnchorsAndPosition( 0, 1, 0,5, 0,5, 58, 126, -34, 34 )
	f1_local2:addElement( f1_local5 )
	f1_local2[0xB2805BEA6897965] = f1_local5
	f0_local0( f1_local2, f1_local3, f1_arg1 )
	return f1_local2
end

MenuBuilder.registerType( 0x4F5B0BF5DFE7231, SocialProfileCardSmallEmpty )
LockTable( _M )
